<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <AssemblyName>OohelpSoft.Extensions.WindowsCredentials</AssemblyName>
        <RootNamespace>OohelpSoft.WindowsCredentials</RootNamespace>

        <Version>1.0.1</Version>

        <Authors>Andrey Slusarev</Authors>
        <Company>OoHelp.Net</Company>
        <Copyright>© 2026 Andrey Slusarev (OoHelp.Net)</Copyright>

        <PackageId>$(AssemblyName)</PackageId>

        <Description>
            Provides secure storage and retrieval of username and password credentials using Windows Credential Manager, along with the native Windows credential prompt.
        </Description>

        <PackageTags>
            Windows;Credentials;CredentialManager;Win32;Authentication;Security
        </PackageTags>
        
        <PackageProjectUrl>https://github.com/Jugius/OohelpSoft.Extensions.WindowsCredentials</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/Jugius/OohelpSoft.Extensions.WindowsCredentials.git</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>

        <AnalysisMode>All</AnalysisMode>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SonarAnalyzer.CSharp" Version="10.34.0.3385">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md"
              Pack="true"
              PackagePath="\" />
    </ItemGroup>

</Project>
