<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <AssemblyName>OohelpSoft.Extensions.WindowsCredentials</AssemblyName>
        <RootNamespace>OohelpSoft.WindowsCredentials</RootNamespace>

        <Version>1.0.0</Version>

        <Authors>Andrey Slusarev</Authors>
        <Company>OoHelp.Net</Company>
        <Copyright>© 2026 Andrey Slusarev (OoHelp.Net)</Copyright>

        <PackageId>$(AssemblyName)</PackageId>

        <Description>
            Provides secure storage and retrieval of username and password credentials using Windows Credential Manager, along with the native Windows credential prompt.
        </Description>

        <PackageTags>
            Windows;Credentials;CredentialManager;Win32;Authentication;Security
        </PackageTags>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    </PropertyGroup>

</Project>
